# # get list of versions from here
# # https://github.com/microsoft/vscode-dev-containers/tree/main/containers/codespaces-linux/history
# # or run
# # devcontainer-info content-url from a base environment
# FROM mcr.microsoft.com/vscode/devcontainers/universal:2.0.2

# ENV HOME /home/codespace/
# WORKDIR /installations

# # Install Julia
# RUN wget https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.6-linux-x86_64.tar.gz && \
#     tar -xzf julia-1.6.6-linux-x86_64.tar.gz && \
#     rm julia-1.6.6-linux-x86_64.tar.gz
# ENV PATH=/installations/julia-1.6.6/bin:$PATH

# # COPY Project.toml $HOME/.julia/environments/v1.6/
# # COPY Manifest.toml $HOME/.julia/environments/v1.6/
# # RUN julia -e 'import Pkg; Pkg.instantiate()'

# WORKDIR $CODESPACE_VSCODE_FOLDER