# Validation of `Mycelia.Rhizomorph.estimate_residual_error` against KNOWN error rates.
#
# WHY THIS EXISTS
# A CANDIDATE k-selection rule, `k >= 1/e - 1`, would consume an estimated
# per-base error rate. That rule is only as good as `e`. This script
#
# PROVENANCE (corrected 2026-08-08): this header previously attributed that rule
# to "the Rhizomorph pre-registration". It is NOT there — searched the
# pre-registration plan (577 lines) and the whole manuscript directory of the
# rhizomorph-paper repository, no match. The rule lives in
# `src/development/intelligent-assembly.jl` (a file `Mycelia.jl` does not
# include) and in `tutorials/18_advanced_assembly_theory_and_practice.jl` (broken
# on master), and traces to 2020 Mycelia-Dev notes. A PROPOSED and UNRATIFIED
# decision record suggests registering it; proposing is not registering. The
# README carried the same error and was corrected first — this file is the
# originating copy and was missed in that pass.
#
# measures the estimator's bias and variance against ground truth that is exact by
# construction, and reports its TWO COMPONENTS SEPARATELY, because
# `estimate_residual_error` returns `max(kmer_component, quality_component)` and a
# combined number hides which signal is driving it.
#
# GROUND TRUTH IS EXACT HERE, BY DESIGN
# Reads are generated by mutating a known reference at a known per-base rate. No
# aligner and no read simulator is involved, so `true_error` is the parameter that
# was applied, not a measurement of it. That is deliberate: a Badread-based check
# would confound estimator bias with simulator-model error. Badread validation is a
# separate, later step and belongs on HPC.
#
# TWO PRE-STATED PREDICTIONS (recorded before the first run, so the result can
# falsify them rather than be fitted to them):
#
#   P1 COVERAGE BIAS. `_kmer_spectrum_residual_error` calls a k-mer "solid" at
#      count >= solid_min (default 2). At low coverage even ERROR-FREE genomic
#      k-mers occur once, so they are counted as non-solid, `solid_fraction`
#      collapses, and the estimate is biased HIGH. Predict: large positive bias at
#      C=5-10, shrinking as coverage rises. This matters because an over-estimated
#      e drives k = 1/e - 1 DOWN, toward the degenerate small-k regime.
#
#   P2 STRAND BIAS. The estimator hashes with `_dynamic_k_window_hash`, which is
#      NOT canonical, while the same file defines `_dynamic_k_canonical_window_hash`
#      whose comment warns that non-canonical hashing counts a locus and its
#      reverse complement as two different k-mers, "HALVING the measured coverage on
#      both-strand read sets". Predict: at matched true error and coverage, the
#      double-strand estimate is biased HIGHER than the single-strand estimate.
#
# A third effect is EXPECTED BEHAVIOUR, not a defect, and is measured to quantify
# it: an indel shifts the frame and destroys every k-mer spanning it, so
# indel-bearing reads should read as a higher EFFECTIVE error than their per-base
# rate. The docstring says as much. It still matters for the k rule, because the
# rule consumes the number as if it were the per-base rate.
#
# Usage (single process, small genome, no external tools):
#   julia --project=. benchmarking/validate_estimate_residual_error.jl
#   julia --project=. benchmarking/validate_estimate_residual_error.jl --smoke

import Mycelia
import Random
import Statistics
import FASTX
import Printf

const SMOKE = "--smoke" in ARGS

const GENOME_LENGTH = SMOKE ? 5_000 : 20_000
const READ_LENGTH = 5_000
const TRUE_ERRORS = SMOKE ? [0.01, 0.10] : [0.001, 0.01, 0.05, 0.10]
const COVERAGES = SMOKE ? [10, 50] : [5, 10, 30, 50, 100]
const STRAND_MODES = [:single, :double]
const ERROR_MODES = [:substitution, :indel_heavy]
const SEEDS = SMOKE ? [42] : [42, 123, 456]

# How the reads' Phred relates to their ACTUAL error rate. This axis exists because
# `estimate_residual_error` returns `max(kmer_component, quality_component)`, so a
# perfectly calibrated Phred makes the combined estimate look exact no matter how the
# k-mer component behaves — which is what the first smoke run showed, and is not a
# property of the estimator so much as of the test.
#   :calibrated    Q = -10log10(e). Best case; does not exist on real data.
#   :overconfident Q claims 3x better than truth. This is the documented ONT failure
#                  mode (medaka / DeepVariant / Clair3 all REPLACE basecaller Phred).
#   :absent        no quality at all (plain sequences), isolating the k-mer component,
#                  which is the only signal guaranteed to be available.
const QUALITY_MODES = SMOKE ? [:calibrated, :absent] :
                      [:calibrated, :overconfident, :absent]

const BASES = ['A', 'C', 'G', 'T']

const OUTPUT_PATH = joinpath(@__DIR__, "results", "estimate_residual_error_validation",
    SMOKE ? "validation_smoke.tsv" : "validation.tsv")

function random_reference(rng::Random.AbstractRNG, length_bp::Int)::String
    return String([rand(rng, BASES) for _ in 1:length_bp])
end

function reverse_complement(sequence::String)::String
    complement = Dict('A' => 'T', 'C' => 'G', 'G' => 'C', 'T' => 'A')
    return String([complement[character] for character in Iterators.reverse(sequence)])
end

# Apply errors at a known per-base rate. In :substitution mode every error event is a
# substitution. In :indel_heavy mode the SAME per-base budget is split evenly between
# substitutions and single-base indels, so `true_error` means the same thing in both
# modes and the two are directly comparable.
function apply_errors(rng::Random.AbstractRNG, sequence::String, error_rate::Float64,
        mode::Symbol)::String
    output = Char[]
    sizehint!(output, length(sequence))
    for character in sequence
        if rand(rng) < error_rate
            if mode == :substitution || rand(rng) < 0.5
                alternatives = filter(base -> base != character, BASES)
                push!(output, rand(rng, alternatives))
            elseif rand(rng) < 0.5
                # deletion: emit nothing
            else
                # insertion: keep the base, add a random one after it
                push!(output, character)
                push!(output, rand(rng, BASES))
            end
        else
            push!(output, character)
        end
    end
    return String(output)
end

# Phred character for the reported error rate. `:overconfident` reports a rate 3x
# LOWER than the truth, the direction real basecallers err in.
function phred_char(error_rate::Float64, quality_mode::Symbol)::Char
    reported = quality_mode == :overconfident ? error_rate / 3 : error_rate
    q_value = reported <= 0.0 ? 60 : round(Int, -10.0 * log10(reported))
    return Char(clamp(q_value, 0, 60) + 33)
end

function simulate_reads(rng::Random.AbstractRNG, reference::String, coverage::Int,
        error_rate::Float64, mode::Symbol, strand::Symbol, quality_mode::Symbol)
    read_count = max(1, cld(coverage * length(reference), READ_LENGTH))
    quality_char = phred_char(error_rate, quality_mode)
    # `:absent` yields plain strings, which the estimator accepts and for which
    # `_quality_residual_error` returns `nothing` — isolating the k-mer component.
    records = quality_mode == :absent ? String[] : FASTX.FASTQ.Record[]
    max_start = max(1, length(reference) - READ_LENGTH + 1)
    for index in 1:read_count
        start_index = rand(rng, 1:max_start)
        stop_index = min(length(reference), start_index + READ_LENGTH - 1)
        fragment = reference[start_index:stop_index]
        # Flip a DETERMINISTIC half rather than a random half. This keeps :single and
        # :double a genuinely PAIRED comparison: both arms draw identical fragments and
        # identical error draws from the RNG, so the only difference between them is
        # strand orientation. A `rand()` here would desynchronise the two streams and
        # confound the strand effect with different reads.
        if strand == :double && iseven(index)
            fragment = reverse_complement(fragment)
        end
        observed = apply_errors(rng, fragment, error_rate, mode)
        isempty(observed) && continue
        if quality_mode == :absent
            push!(records, observed)
        else
            push!(records,
                FASTX.FASTQ.Record("read$(index)", observed,
                    repeat(string(quality_char), length(observed))))
        end
    end
    return records
end

function main()
    mkpath(dirname(OUTPUT_PATH))
    rows = String[]
    push!(rows,
        join(
            ["true_error", "coverage", "strand", "error_mode", "quality_mode", "seed",
                "n_reads", "kmer_component", "quality_component", "combined",
                "kmer_bias", "combined_bias", "implied_k_true", "implied_k_estimated"],
            "\t"))

    total = length(TRUE_ERRORS) * length(COVERAGES) * length(STRAND_MODES) *
            length(ERROR_MODES) * length(QUALITY_MODES) * length(SEEDS)
    cell = 0

    for true_error in TRUE_ERRORS, coverage in COVERAGES, strand in STRAND_MODES,
        mode in ERROR_MODES, quality_mode in QUALITY_MODES, seed in SEEDS
        cell += 1
        rng = Random.MersenneTwister(seed)
        reference = random_reference(rng, GENOME_LENGTH)
        reads = simulate_reads(rng, reference, coverage, true_error, mode, strand,
            quality_mode)

        kmer_component = Mycelia.Rhizomorph._kmer_spectrum_residual_error(reads, 13, 2)
        quality_component = Mycelia.Rhizomorph._quality_residual_error(reads)
        combined = Mycelia.Rhizomorph.estimate_residual_error(reads)

        # What the CANDIDATE k rule would do with each number (see PROVENANCE
        # in the header — this rule is not registered anywhere).
        implied_k_true = max(3, floor(Int, 1 / true_error - 1))
        implied_k_estimated = combined <= 0.0 ? typemax(Int) :
                              max(3, floor(Int, 1 / combined - 1))

        push!(rows,
            join(
                [
                    string(true_error), string(coverage), string(strand), string(mode),
                    string(quality_mode), string(seed), string(length(reads)),
                    Printf.@sprintf("%.6f", kmer_component),
                    quality_component === nothing ? "NA" :
                    Printf.@sprintf("%.6f", quality_component),
                    Printf.@sprintf("%.6f", combined),
                    Printf.@sprintf("%.6f", kmer_component - true_error),
                    Printf.@sprintf("%.6f", combined - true_error),
                    string(implied_k_true), string(implied_k_estimated)
                ],
                "\t"))

        Printf.@printf("[%3d/%3d] e=%.3f C=%3d %-6s %-12s %-13s seed=%3d -> kmer=%.4f qual=%s combined=%.4f (bias %+.4f)  k: %d -> %d\n",
            cell, total, true_error, coverage, string(strand), string(mode),
            string(quality_mode), seed,
            kmer_component,
            quality_component === nothing ? "NA" :
            Printf.@sprintf("%.4f", quality_component),
            combined, combined - true_error, implied_k_true, implied_k_estimated)
    end

    open(OUTPUT_PATH, "w") do io
        for row in rows
            println(io, row)
        end
    end
    println("\nWrote: ", OUTPUT_PATH)
    println("Cells: ", total)
end

main()
