# originally started with this but feels better to not work on the default environment
# install me with:
# conda env update --file environment.yml <- did work
# mamba env update --file environment.yml
# conda env update -n base --file environment.yml <- didn't work
# name: base

# to create
# conda env create --file environment.yml
# or to move quicker
# conda install mamba
# mamba env create --file environment.yml

# To determine how to update
# should be able to record me with either of the following
# https://github.com/conda/conda/issues/9399
# conda env export --no-builds
# conda env export --no-builds --from-history

# had to install centrifuge from source
# dropped sourmash because it's not a very inclusive database

# to use:
# conda activate viral-pangenome-discovery
name: viral-pangenome-discovery
# channel_priority: strict
channels:
  - conda-forge
  - bioconda
dependencies:
  - ncbi-datasets-cli
  - snakemake
  - sra-tools
  - bwa
  - bowtie2
  - kraken2
  - spades
  - megahit
  - blast
  - seqtk
  - minimap2
  - samtools
  - fastqc
  - trim-galore
  - seqkit
  - virsorter=2
  - pyrodigal
  - prodigal
  - diamond
  - mmseqs2
  
  
# -c conda-forge -c bioconda ncbi-datasets-cli fastani snakemake minimap2 samtools blast mash bwa fastqc trim-galore prodigal diamond multiqc megahit qualimap taxonkit seqtk bedtools seqkit sra-tools kraken2 mmseqs2
