name: CI

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['lts']
        # julia-version: ['1', 'lts']
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2.6.1
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache Julia packages
        id: cache-artifacts
        uses: actions/cache@v3
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-${{ matrix.julia-version }}-artifacts-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ matrix.julia-version }}-artifacts-

      - name: Install dependencies
        if: steps.cache-artifacts.outputs.cache-hit != 'true'
        run: julia --project=. -e 'using Pkg; Pkg.build("Conda"); Pkg.instantiate();'

      - name: Run tests with coverage
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.build("Conda"); Pkg.test(coverage=true);'

      - name: Submit coverage
        run: julia --project=. -e 'using Coverage; Codecov.submit(process_folder())'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}