name: CI

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['lts']
        # julia-version: ['1', 'lts']
    env:
      GKS_WSTYPE: "100"
      MYCELIA_RUN_EXTERNAL: "false"
      MYCELIA_SHOW_PLOTS: "false"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2.6.1
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Install dependencies
        run: julia --color=yes --project=. -e 'import Pkg; Pkg.instantiate(); Pkg.build();'

      - name: Run tests with coverage
        run: julia --color=yes --project=. -e 'import Pkg; Pkg.test(coverage=true);'

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
