name: CI

on:
  push:
    branches:
      - master # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:
    branches:
      - master # update to match your development branch (master, main, dev, trunk, ...)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'
      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.test(coverage=true)'
      - name: Submit coverage
        run: julia -e 'using Coverage; Codecov.submit(process_folder())'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}