name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    env:
      GKS_WSTYPE: "100"
      MYCELIA_SHOW_PLOTS: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: 'lts'
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --color=yes --project=docs/ -e 'import Pkg; Pkg.develop(Pkg.PackageSpec(path=pwd())); Pkg.instantiate();'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --color=yes --project=docs/ -e 'import Pkg; Pkg.build(); include("docs/make.jl")'
